package com.epam.cafe.command.factory;

public enum CommandType {
    AUTHORIZE,

    CHOOSE_LANGUAGE,
    LOGOUT,

    GET_CLIENTS,

    GET_BONUSES_ADMIN,
    DELETE_BONUS,

    SPECIFY_NEW_BONUS,
    ADD_BONUS,

    MANAGE_CLIENT_INFORMATION,
    SAVE_CLIENT_CHANGES,

    GET_ALL_DISHES,
    DELETE_DISH,

    SPECIFY_NEW_DISH,
    ADD_DISH,

    MANAGE_DISH_INFORMATION,
    SAVE_DISH_CHANGES,

    GET_CLIENT_MENU,
    SAVE_DISH_ORDER,

    GET_CURRENT_ORDERS,
    DELETE_ORDER,

    GET_PREVIOUS_ORDERS,
    RATE_ORDER,
    LEAVE_COMMENT,

    GET_GLOBAL_ORDERS,

    GET_BONUSES_CLIENT,

    SHOW_BASKET,
    REMOVE_DISH_ORDER,
    REMOVE_ALL_DISH_ORDER,
    ORDER
}
